#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


>&2 echo 'Start staging setup'

>&2 echo 'Make migrations'
poetry run python manage.py makemigrations --settings={{project_name}}.settings.local
>&2 echo 'Migrating databse'
poetry run python manage.py migrate --settings={{project_name}}.settings.local
>&2 echo 'Collecting static files'
poetry run python manage.py collectstatic --ignore ts --ignore debug_toolbar --ignore django_extensions --noinput --settings={{project_name}}.settings.local

TMPFILE=$(mktemp) || { echo "Failed to create temp file"; exit 1; }

set +e
if [ "$DJANGO_SUPERUSER_USERNAME" ]
then
    >&2 echo 'Creating superuser'
    poetry run python manage.py createsuperuser --settings={{project_name}}.settings.local \
        --noinput \
        --username $DJANGO_SUPERUSER_USERNAME \
        --email $DJANGO_SUPERUSER_EMAIL 2> $TMPFILE
        EXIT_CODE=$?
        set -e
fi

$@

# Check if the command failed
if [[ $EXIT_CODE -ne 0 ]]; then
    # Check if the error matches the specific message
    if grep -q "CommandError: Error: That username is already taken." "$TMPFILE"; then
        echo "Warning: Username already taken. Continuing script..."
    else
        # Display unexpected error and exit
        echo "Unexpected error:"
        cat "$TMPFILE"
        rm "$TMPFILE"
        exit $EXIT_CODE
    fi
fi

# Cleanup and continue
rm "$TMPFILE"
echo "Script continues..."

>&2 echo 'Starting test server'
poetry run python manage.py runserver 0.0.0.0:8000
